#!/bin/bash

set -eu

name=$1

for col in $(seq 0 $((0x`cat /sys/fs/castle-fs/collections/number`))); do 
    col=$(printf '%x' $col)
    [ -e /sys/fs/castle-fs/collections/$col/name ] || continue; 

    if [ "$(cat /sys/fs/castle-fs/collections/$col/name)" = ${name} ]; then
	echo $col
	exit 0
    fi
done
